SELECT fname, lname FROM member;
SELECT * FROM member;
SELECT fname, area FROM member;
SELECT DISTINCT type FROM books;
SELECT fname FROM member WHERE SUBSTR(fname, 2, 1) = 'a';
SELECT lname FROM member WHERE lname LIKE 's%' OR lname LIKE 'j%';
SELECT * FROM member WHERE SUBSTR(area, 2, 1) = 'B';
SELECT * FROM member WHERE area IN ('MYL', 'CBE', 'DEL');
SELECT * FROM member WHERE phone_no > 9800000000;
SELECT * FROM transaction WHERE EXTRACT(MONTH FROM issue_date) = 9;
SELECT * FROM transaction WHERE member_id IN ('M03', 'M04');
SELECT * FROM books WHERE type IN ('CSE', 'ECE');
SELECT * FROM books WHERE price > 3500 AND price <= 5000;
SELECT *, price * 15 AS newprice FROM books WHERE price > 5000;
SELECT *, price * 15 AS new_price FROM books WHERE price > 5000;
SELECT * FROM books ORDER BY title;
SELECT title, type FROM books WHERE type != 'IC';
SELECT title, SQRT(price) AS square_root_price FROM books;
SELECT title, price / (price - 1000) AS result FROM books WHERE title = 'Digital Design';
SELECT fname, lname, area, member_id FROM member WHERE phone_no IS NULL;
SELECT fname FROM member WHERE lname IS NULL;
SELECT book_id, title, type FROM books WHERE author LIKE 'M%';
SELECT book_id, t_id FROM transaction WHERE t_id < 't05';
